"""empty message

Revision ID: 0e4741de3b0c
Revises: 9aa82a297660
Create Date: 2024-07-25 00:14:28.779073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.logic.models.symbol import Action

# revision identifiers, used by Alembic.
revision: str = "0e4741de3b0c"
down_revision: Union[str, None] = "9aa82a297660"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(sa.sql.text("DELETE FROM symbol_action;"))
    conn.execute(
        sa.sql.text(
            f"""INSERT INTO symbol_action (user_id, ticker, amount, action, created_at, price)
            SELECT owner_id, code, amount, {Action.buy}, NOW() AT TIME ZONE 'UTC', 0.0 FROM symbols;"""
        )
    )
    op.drop_table("symbols")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "symbols",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            "owner_id", sa.BIGINT(), autoincrement=False, nullable=False
        ),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("amount", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name="symbols_owner_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="symbols_pkey"),
    )
    # ### end Alembic commands ###
