"""empty message

Revision ID: 1b106969ea93
Revises: f5152a8a86b3
Create Date: 2024-07-08 16:32:15.777366

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b106969ea93"
down_revision: Union[str, None] = "f5152a8a86b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "symbol_action", sa.Column("ticker", sa.String(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("symbol_action", "ticker")
    # ### end Alembic commands ###
