"""empty message

Revision ID: 3f9f471448a0
Revises: 03cd1d35b629
Create Date: 2024-06-11 14:16:17.439976

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.logic.models import USER_DEFAULT_ROLE

# revision identifiers, used by Alembic.
revision: str = "3f9f471448a0"
down_revision: Union[str, None] = "03cd1d35b629"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Integer(),
            server_default=str(USER_DEFAULT_ROLE.value),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
