"""empty message

Revision ID: 71b46285db79
Revises: 904456dd87ad
Create Date: 2024-06-27 18:44:27.592945

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "71b46285db79"
down_revision: Union[str, None] = "904456dd87ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "balance_change",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("balance_change", "created_at")
    # ### end Alembic commands ###
