"""empty message

Revision ID: 8bc2d4d94fc3
Revises: e80eee085b00
Create Date: 2024-08-14 01:09:34.634950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.logic.models.currency import Reason, Action

# revision identifiers, used by Alembic.
revision: str = "8bc2d4d94fc3"
down_revision: Union[str, None] = "e80eee085b00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.add_column(
        "currencies_action",
        sa.Column("reason", sa.Integer(), nullable=False, server_default="0"),
    )
    conn.execute(
        sa.text(
            "UPDATE currencies_action"
            + f" SET reason = CASE WHEN action = {Action.add}"
            + f" THEN {Reason.unknown_add} ELSE {Reason.unknown_remove} END"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currencies_action", "reason")
    # ### end Alembic commands ###
