"""empty message

Revision ID: 960ce3b87a54
Revises: c0b367b53b41
Create Date: 2024-07-08 17:25:10.311840

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "960ce3b87a54"
down_revision: Union[str, None] = "c0b367b53b41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "symbol_action",
        sa.Column(
            "price", sa.Float(), server_default=str(0.0), nullable=False
        ),
    )
    op.alter_column(
        "symbol_action",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "symbol_action",
        "amount",
        existing_type=sa.Integer(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.drop_column("symbol_action", "price")
    # ### end Alembic commands ###
