"""empty message

Revision ID: cc0f44cad60c
Revises: f33ae154400e
Create Date: 2024-08-21 12:33:23.584653

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc0f44cad60c"
down_revision: Union[str, None] = "f33ae154400e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_symbol_info",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("currency_action", sa.BigInteger(), nullable=False),
        sa.Column("symbol_ticker", sa.String(), nullable=False),
        sa.Column("symbol_amount", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["currency_action"],
            ["currencies_action.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency_symbol_info")
    # ### end Alembic commands ###
