"""empty message

Revision ID: d769b796b3fe
Revises: e59304de9f1a
Create Date: 2024-08-03 23:02:12.278346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.logic.abstract.storages.currency import MAIN_CURRENCY
from app.logic.models.currency import Action

# revision identifiers, used by Alembic.
revision: str = "d769b796b3fe"
down_revision: Union[str, None] = "e59304de9f1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(
        sa.sql.text(
            f"""INSERT INTO currencies_action (user_id, ticker, action, amount, price, created_at)
            SELECT id, '{MAIN_CURRENCY}', {Action.buy}, balance, 0.0, NOW() AT TIME ZONE 'UTC' FROM users;"""
        )
    )
    op.drop_column("users", "balance")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "balance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
