"""empty message

Revision ID: e59304de9f1a
Revises: 0e4741de3b0c
Create Date: 2024-07-27 21:41:38.341144

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e59304de9f1a"
down_revision: Union[str, None] = "0e4741de3b0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("ticker", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "amount",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="currencies_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="currencies_pkey"),
    )
    # ### end Alembic commands ###
